namespace MultiplayerSnake;

public class Utilities
{
    public static List<double[]> PointsOnLine(double x1, double y1, double x2, double y2) // PointsOnLine function generated by ChatGPT.
    {
        List<double[]> coordinates = new List<double[]>();
        if (Convert.ToInt32(x1) == Convert.ToInt32(x2))
        {
            var minY = Math.Min(y1, y2);
            var maxY = Math.Max(y1, y2);
            for (var y = minY; y <= maxY; y++)
            {
                coordinates.Add(new[] { x1, y });
            }
        }
        else
        {
            var slope = (y2 - y1) / (x2 - x1);
            var distance = Math.Sqrt(Math.Pow(x2 - x1, 2) + Math.Pow(y2 - y1, 2));
            var numPoints = (int)Math.Ceiling(distance);
            for (var i = 0; i <= numPoints; i++)
            {
                var x = x1 + i * (x2 - x1) / numPoints;
                var y = y1 + slope * (x - x1);
                coordinates.Add(new[] { x, y });
            }
        }
        return coordinates;
    }

    public static int Location(int x, int y)
    {
        return Console.WindowWidth * Console.WindowHeight - Console.WindowWidth + x - Console.WindowWidth * y + (Console.WindowWidth - 1);
    }
}